/**
 * Gazetteer per la mappa del Mediterraneo: catalogo di città (con coordinate) e
 * mappatura autore → città. Il luogo scelto è quello più identificativo per
 * l'autore (in genere la città natale, altrimenti il centro di attività), così
 * che la mappa racconti la geografia delle fonti che confluiscono in Dante.
 * Molte opere condividono l'autore, quindi molte opere condividono il luogo.
 */

export interface Luogo {
  /** Nome mostrato sulla mappa; funge anche da chiave in LUOGHI. */
  nome: string;
  lat: number;
  lng: number;
}

export const LUOGHI: Record<string, Luogo> = {
  // --- Mondo greco: Egeo e Ionia ---
  Atene: { nome: "Atene", lat: 37.98, lng: 23.73 },
  Mileto: { nome: "Mileto", lat: 37.53, lng: 27.28 },
  Efeso: { nome: "Efeso", lat: 37.94, lng: 27.34 },
  Colofone: { nome: "Colofone", lat: 38.1, lng: 27.15 },
  Teo: { nome: "Teo", lat: 38.18, lng: 26.78 },
  Smirne: { nome: "Smirne", lat: 38.42, lng: 27.14 },
  Samo: { nome: "Samo", lat: 37.75, lng: 26.98 },
  Chio: { nome: "Chio", lat: 38.37, lng: 26.14 },
  Mitilene: { nome: "Mitilene", lat: 39.11, lng: 26.55 },
  Abdera: { nome: "Abdera", lat: 40.94, lng: 24.98 },
  Taso: { nome: "Taso", lat: 40.68, lng: 24.65 },
  Clazomene: { nome: "Clazomene", lat: 38.36, lng: 26.77 },
  Paro: { nome: "Paro", lat: 37.08, lng: 25.15 },
  Ceo: { nome: "Ceo", lat: 37.63, lng: 24.34 },
  Caristo: { nome: "Caristo", lat: 37.99, lng: 24.42 },
  Tebe: { nome: "Tebe", lat: 38.32, lng: 23.32 },
  Ascra: { nome: "Ascra", lat: 38.28, lng: 23.08 },
  Cheronea: { nome: "Cheronea", lat: 38.49, lng: 22.84 },
  Sparta: { nome: "Sparta", lat: 37.07, lng: 22.43 },
  Creta: { nome: "Creta", lat: 35.3, lng: 25.15 },
  Alicarnasso: { nome: "Alicarnasso", lat: 37.04, lng: 27.42 },
  Cos: { nome: "Cos", lat: 36.89, lng: 27.29 },
  Nicomedia: { nome: "Nicomedia", lat: 40.77, lng: 29.92 },
  Ierapoli: { nome: "Ierapoli", lat: 37.92, lng: 29.13 },
  Costantinopoli: { nome: "Costantinopoli", lat: 41.01, lng: 28.98 },
  // --- Levante e Oriente ---
  Cizio: { nome: "Cizio", lat: 34.92, lng: 33.63 },
  Soli: { nome: "Soli", lat: 36.75, lng: 34.6 },
  Seleucia: { nome: "Seleucia", lat: 36.38, lng: 33.93 },
  "Calcide di Siria": { nome: "Calcide di Siria", lat: 34.6, lng: 36.7 },
  Antiochia: { nome: "Antiochia", lat: 36.2, lng: 36.16 },
  Gerasa: { nome: "Gerasa", lat: 32.28, lng: 35.89 },
  Betlemme: { nome: "Betlemme", lat: 31.7, lng: 35.2 },
  Baghdad: { nome: "Baghdad", lat: 33.31, lng: 44.36 },
  Hamadan: { nome: "Hamadan", lat: 34.8, lng: 48.52 },
  // --- Nord Africa ed Egitto ---
  Alessandria: { nome: "Alessandria", lat: 31.2, lng: 29.92 },
  Cartagine: { nome: "Cartagine", lat: 36.85, lng: 10.32 },
  Madaura: { nome: "Madaura", lat: 36.08, lng: 7.6 },
  Ippona: { nome: "Ippona", lat: 36.9, lng: 7.75 },
  "Cesarea di Mauretania": { nome: "Cesarea di Mauretania", lat: 36.6, lng: 2.19 },
  // --- Sicilia e Magna Grecia ---
  Siracusa: { nome: "Siracusa", lat: 37.08, lng: 15.29 },
  Lentini: { nome: "Lentini", lat: 37.28, lng: 15.0 },
  Imera: { nome: "Imera", lat: 37.97, lng: 13.82 },
  Agira: { nome: "Agira", lat: 37.66, lng: 14.52 },
  Alcamo: { nome: "Alcamo", lat: 37.98, lng: 12.96 },
  Messina: { nome: "Messina", lat: 38.19, lng: 15.55 },
  Reggio: { nome: "Reggio", lat: 38.11, lng: 15.65 },
  Elea: { nome: "Elea", lat: 40.16, lng: 15.15 },
  Taranto: { nome: "Taranto", lat: 40.46, lng: 17.24 },
  Rudiae: { nome: "Rudiae", lat: 40.34, lng: 18.13 },
  Venosa: { nome: "Venosa", lat: 40.96, lng: 15.82 },
  Squillace: { nome: "Squillace", lat: 38.78, lng: 16.52 },
  // --- Italia romana e comunale ---
  Roma: { nome: "Roma", lat: 41.89, lng: 12.49 },
  Napoli: { nome: "Napoli", lat: 40.85, lng: 14.27 },
  Capua: { nome: "Capua", lat: 41.08, lng: 14.25 },
  Suessa: { nome: "Suessa", lat: 41.23, lng: 13.93 },
  Aquino: { nome: "Aquino", lat: 41.49, lng: 13.71 },
  Sulmona: { nome: "Sulmona", lat: 42.05, lng: 13.93 },
  Assisi: { nome: "Assisi", lat: 43.07, lng: 12.62 },
  Bagnoregio: { nome: "Bagnoregio", lat: 42.63, lng: 12.1 },
  Todi: { nome: "Todi", lat: 42.78, lng: 12.41 },
  Volterra: { nome: "Volterra", lat: 43.4, lng: 10.86 },
  Firenze: { nome: "Firenze", lat: 43.77, lng: 11.26 },
  Arezzo: { nome: "Arezzo", lat: 43.46, lng: 11.88 },
  Siena: { nome: "Siena", lat: 43.32, lng: 11.33 },
  Lucca: { nome: "Lucca", lat: 43.84, lng: 10.5 },
  Pistoia: { nome: "Pistoia", lat: 43.93, lng: 10.91 },
  Bologna: { nome: "Bologna", lat: 44.49, lng: 11.34 },
  Genova: { nome: "Genova", lat: 44.41, lng: 8.93 },
  Sarsina: { nome: "Sarsina", lat: 43.92, lng: 12.14 },
  Mantova: { nome: "Mantova", lat: 45.16, lng: 10.79 },
  Verona: { nome: "Verona", lat: 45.44, lng: 10.99 },
  Padova: { nome: "Padova", lat: 45.41, lng: 11.88 },
  Venezia: { nome: "Venezia", lat: 45.44, lng: 12.32 },
  Como: { nome: "Como", lat: 45.81, lng: 9.08 },
  Cremona: { nome: "Cremona", lat: 45.13, lng: 10.02 },
  Aosta: { nome: "Aosta", lat: 45.74, lng: 7.32 },
  // --- Iberia ---
  Cordova: { nome: "Cordova", lat: 37.88, lng: -4.78 },
  Siviglia: { nome: "Siviglia", lat: 37.39, lng: -5.99 },
  Malaga: { nome: "Malaga", lat: 36.72, lng: -4.42 },
  Bilbilis: { nome: "Bilbilis", lat: 41.38, lng: -1.6 },
  Calagurris: { nome: "Calagurris", lat: 42.3, lng: -1.96 },
  // --- Francia occitana e del nord ---
  Poitiers: { nome: "Poitiers", lat: 46.58, lng: 0.34 },
  Ventadour: { nome: "Ventadour", lat: 45.3, lng: 1.95 },
  Hautefort: { nome: "Hautefort", lat: 45.26, lng: 1.14 },
  "Ribérac": { nome: "Ribérac", lat: 45.25, lng: 0.34 },
  Blaye: { nome: "Blaye", lat: 45.13, lng: -0.66 },
  Troyes: { nome: "Troyes", lat: 48.3, lng: 4.08 },
  "Orléans": { nome: "Orléans", lat: 47.9, lng: 1.9 },
  Parigi: { nome: "Parigi", lat: 48.85, lng: 2.35 },
  Clairvaux: { nome: "Clairvaux", lat: 48.15, lng: 4.79 },
  Lione: { nome: "Lione", lat: 45.76, lng: 4.83 },
  Lilla: { nome: "Lilla", lat: 50.63, lng: 3.06 },
  Aurillac: { nome: "Aurillac", lat: 44.93, lng: 2.44 },
  Laon: { nome: "Laon", lat: 49.56, lng: 3.62 },
  // --- Europa germanica e britannica ---
  Colonia: { nome: "Colonia", lat: 50.94, lng: 6.96 },
  Fulda: { nome: "Fulda", lat: 50.55, lng: 9.68 },
  "San Gallo": { nome: "San Gallo", lat: 47.42, lng: 9.38 },
  York: { nome: "York", lat: 53.96, lng: -1.08 },
  Jarrow: { nome: "Jarrow", lat: 54.98, lng: -1.47 },
};

export const AUTORE_LUOGO: Record<string, string> = {
  "Al-Ghazali": "Baghdad",
  "Alano di Lilla": "Lilla",
  "Alberto Magno": "Colonia",
  "Alcuino di York": "York",
  "Albio Tibullo": "Roma",
  Alceo: "Mitilene",
  Alcmane: "Sparta",
  Anacreonte: "Teo",
  Anassagora: "Clazomene",
  Anassimandro: "Mileto",
  Anassimene: "Mileto",
  Andocide: "Atene",
  "Anicio Manlio Severino Boezio": "Roma",
  "Anonimi (tradizione omerica)": "Smirne",
  Anonimo: "Firenze",
  "Anselmo d'Aosta": "Aosta",
  Antifona: "Atene",
  "Antonio abate (vita di Atanasio)": "Alessandria",
  "Apollodoro di Caristo": "Caristo",
  "Arato di Soli": "Soli",
  Archiloco: "Paro",
  Archimede: "Siracusa",
  Aristofane: "Atene",
  Aristotele: "Atene",
  "Arnaut Daniel": "Ribérac",
  Arriano: "Nicomedia",
  "Atanasio di Alessandria": "Alessandria",
  "Aulo Persio Flacco": "Volterra",
  "Aurelio Agostino": "Ippona",
  Bacchilide: "Ceo",
  "Beda il Venerabile": "Jarrow",
  "Bernardo di Chiaravalle": "Clairvaux",
  "Bernart de Ventadorn": "Ventadour",
  "Bertran de Born": "Hautefort",
  "Bonagiunta Orbicciani": "Lucca",
  "Bonaventura da Bagnoregio": "Bagnoregio",
  "Brunetto Latini": "Firenze",
  Catullo: "Verona",
  "Cecco Angiolieri": "Siena",
  "Cecilio Cipriano": "Cartagine",
  Chionide: "Atene",
  "Chrétien de Troyes": "Troyes",
  "Cielo d'Alcamo": "Alcamo",
  "Cino da Pistoia": "Pistoia",
  "Circolo di Messalla (Corpus Tibullianum)": "Roma",
  "Claudio Tolomeo": "Alessandria",
  "Clemente Alessandrino": "Alessandria",
  "Crisippo di Soli": "Soli",
  "Dante Alighieri": "Firenze",
  "Decimo Giunio Giovenale": "Aquino",
  Democrito: "Abdera",
  Demostene: "Atene",
  Dinarco: "Atene",
  "Dinone di Colofone": "Colofone",
  "Diodoro Siculo": "Agira",
  "Diogene Laerzio": "Atene",
  "Duride di Samo": "Samo",
  "Egemone di Taso": "Taso",
  Epicuro: "Atene",
  Epimenide: "Creta",
  Eraclito: "Efeso",
  Erodoto: "Alicarnasso",
  Eschilo: "Atene",
  Eschine: "Atene",
  Esiodo: "Ascra",
  Esopo: "Samo",
  Eubulo: "Atene",
  "Euclide di Alessandria": "Alessandria",
  Euripide: "Atene",
  "Evagrio Pontico": "Alessandria",
  "Ferecide di Atene": "Atene",
  "Filone di Alessandria": "Alessandria",
  "Flavio Magno Aurelio Cassiodoro": "Squillace",
  "Francesco d'Assisi": "Assisi",
  "Gaio Giulio Cesare": "Roma",
  "Gaio Lucilio": "Suessa",
  "Gaio Plinio Cecilio Secondo (il Giovane)": "Como",
  "Gaio Sallustio Crispo": "Roma",
  "Gaio Svetonio Tranquillo": "Roma",
  "Gaio Valerio Flacco": "Roma",
  "Gerberto d'Aurillac (poi papa Silvestro II)": "Aurillac",
  "Giacomo da Lentini": "Lentini",
  Giamblico: "Calcide di Siria",
  "Giovanni Scoto Eriugena": "Laon",
  "Giustino (martire)": "Roma",
  "Gneo Nevio": "Capua",
  Gorgia: "Lentini",
  Graziano: "Bologna",
  "Gregorio Magno": "Roma",
  "Guglielmo IX d'Aquitania": "Poitiers",
  "Guido Cavalcanti": "Firenze",
  "Guido Guinizelli": "Bologna",
  "Guido delle Colonne": "Messina",
  "Guillaume de Lorris e Jean de Meun": "Orléans",
  "Guittone d'Arezzo": "Arezzo",
  Ibico: "Reggio",
  "Ibn Rushd (Averroè)": "Cordova",
  "Ibn Sina (Avicenna)": "Hamadan",
  Iperide: "Atene",
  Ippocrate: "Cos",
  "Ireneo di Lione": "Lione",
  Iseo: "Atene",
  "Isidoro di Siviglia": "Siviglia",
  Isocrate: "Atene",
  "Jacopo da Varazze": "Genova",
  "Jacopone da Todi": "Todi",
  "Jaufre Rudel": "Blaye",
  Leucippo: "Mileto",
  "Licurgo di Atene": "Atene",
  Lisia: "Atene",
  "Liutprando di Cremona": "Cremona",
  "Livio Andronico": "Taranto",
  "Luca (evangelista)": "Antiochia",
  "Lucio Anneo Seneca": "Roma",
  "Lucio Apuleio": "Madaura",
  "Marco Anneo Lucano": "Roma",
  "Marco Fabio Quintiliano": "Calagurris",
  "Marco Minucio Felice": "Cartagine",
  "Marco Polo e Rustichello da Pisa": "Venezia",
  "Marco Porcio Catone (il Censore)": "Roma",
  "Marco Tullio Cicerone": "Roma",
  "Marco Valerio Marziale": "Bilbilis",
  "Marziano Capella": "Cartagine",
  "Massimo il Confessore": "Costantinopoli",
  "Melisso di Samo": "Samo",
  Menandro: "Atene",
  "Mosè Maimonide": "Cordova",
  "Nicomaco di Gerasa": "Gerasa",
  "Notker Balbulo": "San Gallo",
  Omero: "Smirne",
  Origene: "Alessandria",
  "Papia di Ierapoli": "Ierapoli",
  Parmenide: "Elea",
  "Petronio Arbitro": "Roma",
  "Pier della Vigna": "Capua",
  "Pietro Abelardo": "Parigi",
  "Pietro Lombardo": "Parigi",
  Pindaro: "Tebe",
  Platone: "Atene",
  Plutarco: "Cheronea",
  "Posidippo (comico)": "Atene",
  "Prisciano di Cesarea": "Cesarea di Mauretania",
  Protagora: "Abdera",
  "Pseudo-Dionigi l'Areopagita": "Atene",
  "Publio Cornelio Tacito": "Roma",
  "Publio Ovidio Nasone": "Sulmona",
  "Publio Papinio Stazio": "Napoli",
  "Publio Terenzio Afro": "Cartagine",
  "Publio Virgilio Marone": "Mantova",
  "Quinto Ennio": "Rudiae",
  "Quinto Orazio Flacco": "Venosa",
  "Quinto Settimio Fiorente Tertulliano": "Cartagine",
  "Rabano Mauro": "Fulda",
  "Restoro d'Arezzo": "Arezzo",
  Saffo: "Mitilene",
  "Salomone ibn Gabirol (Avicebron)": "Malaga",
  "Senarco di Seleucia": "Seleucia",
  Senofane: "Colofone",
  Senofonte: "Atene",
  "Sesto Properzio": "Assisi",
  "Sigieri di Brabante": "Parigi",
  Simonide: "Ceo",
  Sofocle: "Atene",
  "Sofronio Eusebio Girolamo": "Betlemme",
  Solone: "Atene",
  Stesicoro: "Imera",
  Strattis: "Atene",
  Talete: "Mileto",
  Teocrito: "Siracusa",
  Teopompo: "Chio",
  "Tiberio Cazio Silio Italico": "Roma",
  "Tito Livio": "Padova",
  "Tito Lucrezio Caro": "Roma",
  "Tito Maccio Plauto": "Sarsina",
  "Tommaso d'Aquino": "Aquino",
  Tucidide: "Atene",
  "Ugo di San Vittore": "Parigi",
  "Zenone di Cizio": "Cizio",
  "Zenone di Elea": "Elea",
};

export function luogoDiAutore(autore: string): Luogo | null {
  const chiave = AUTORE_LUOGO[autore];
  return chiave ? LUOGHI[chiave] ?? null : null;
}
